# Generated by Django 3.0.3 on 2020-02-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('fridge_is_empty', models.BooleanField()),
                ('time_since', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
