# Generated by Django 3.0.3 on 2020-05-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Fridge', max_length=100, unique=True)),
                ('state', models.CharField(default='Empty', max_length=20)),
                ('floor', models.IntegerField(default=1)),
                ('channel', models.CharField(default='general', max_length=30)),
            ],
        ),
    ]
